In [8]:
import numpy as np
import nrrd

In [12]:
filename = r"solid_400001-segmentation-solid_400001-label.nrrd"
filedata, fileheader = nrrd.read(filename)
print(filedata.shape)

(267, 216, 269)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
s1, s2, s3 = filedata.shape
dims = 301
dim1 = int(301-s1)/2
dim2 = int(301-s2 + 1)/2
dim3 = int(301-s3)/2

cube = np.zeros([301,301,301])
for i in range(s1):
  for j in range(s2):
    for k in range(s3):
      if filedata[i][j][k] == 1:
        cube[i+dim1][j+dim2][k+dim3] = 1


  


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices