In [5]:
import numpy as np
import lineRenderWorldSetup as LR
import cv2

In [17]:
p = r"3dTo2d\orthogonal_view.png"
IMAGE_DIM = 735
DETECTOR_TO_PATIENT = -22

d = IMAGE_DIM - 1

In [44]:
l = createCoordsForImageFrom3d(p)

In [45]:
print(l)

[(-22, 367.0, -367.0)]


In [36]:
a = np.zeros([3,3])
a[0,0] = 1
a[1,0] = 1
#a[0,0] = 1
#a[0, 0] = 1
print(a)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]


In [48]:
im = cv2.imread(p)
cv2.imshow("e", im[:, ::-1, :])
cv2.waitKey(0)


-1