In [1]:
import numpy as np


In [2]:
import math as m


def Rx(theta):
  return np.matrix([[1, 0, 0],
                    [0, m.cos(theta), -m.sin(theta)],
                    [0, m.sin(theta), m.cos(theta)]])


def Ry(theta):
  return np.matrix([[m.cos(theta), 0, m.sin(theta)],
                    [0, 1, 0],
                    [-m.sin(theta), 0, m.cos(theta)]])


def Rz(theta):
  return np.matrix([[m.cos(theta), -m.sin(theta), 0],
                    [m.sin(theta), m.cos(theta), 0],
                    [0, 0, 1]])


In [49]:
d = 462
v = [d, 0, 0]


In [58]:
def rot(p,a1,a2):
  r1 = Rz(m.radians(-a1))
  r2 = Rx(m.radians(a2))
  return p * r1 * r2

In [59]:
print(rot([1,0,0],90,90))


[[ 6.123234e-17  6.123234e-17 -1.000000e+00]]


In [62]:
angles = [(-87, 27), (0, 0), (87, 27), (87, -27), (-75, -22), (-43, -11), (-43, 13), (43, -13), (43, 13)]

points = []
for i in angles:
  p = rot(v,i[0],i[1])
  points.append(p)


In [63]:
for i in range(len(points)):
  print(points[i])

[[  24.17921178 -411.08086899  209.45616455]]
[[462.   0.   0.]]
[[  24.17921178  411.08086899 -209.45616455]]
[[ 24.17921178 411.08086899 209.45616455]]
[[ 119.57439884 -413.76296385 -167.17108867]]
[[ 337.88541015 -309.29427574  -60.12071693]]
[[ 337.88541015 -307.00767926   70.87830757]]
[[337.88541015 307.00767926  70.87830757]]
[[337.88541015 307.00767926 -70.87830757]]
